stages:
  - testing
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DO_ACCESS_TOKEN: $DO_ACCESS_TOKEN

test:
  stage: testing
  image: "docker:latest"
  services:
    - docker:dind
  tags:
    - cicd
  script:
    - docker build -t ocw-backend-test:latest -f Dockerfile.test .
    - docker run -t --rm ocw-backend-test:latest

deploy:
  stage: deploy
  image: "docker:latest"
  when: on_success
  services:
    - docker:dind
  tags:
    - cicd
  only:
    - tags
  before_script:
    - echo $DO_ACCESS_TOKEN | docker login registry.digitalocean.com --username $DO_ACCESS_TOKEN --password-stdin
  script:
    - docker build -t registry.digitalocean.com/ocw-container/ocw-backend:latest -t registry.digitalocean.com/ocw-container/ocw-backend:$CI_COMMIT_TAG .
    - docker push registry.digitalocean.com/ocw-container/ocw-backend:$CI_COMMIT_TAG
    - docker push registry.digitalocean.com/ocw-container/ocw-backend:latest
