version: "3.8"

services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
    env_file: .env.docker
    networks:
      - api_network
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .env.local:/app/.env.local
      - .env:/app/.env
    ports:
      - 8888:8080
    env_file: .env.docker
    depends_on:
      - database
      - minio
      - redis
    networks:
      - api_network
  database:
    ports:
      - 5433:5432
    image: postgres:alpine3.17
    networks:
      - api_network
    volumes:
      - db:/var/lib/postgresql/data
    env_file: .env.docker
  redis:
    ports:
      - 6379:6379
    image: redis:latest
    env_file: .env
    networks:
      - api_network
  mailhog:
    ports:
      - 1025:1025
      - 8025:8025
    image: mailhog/mailhog:latest
    env_file: .env.docker
    networks:
      - api_network

networks:
  api_network:
    name: ocw_network

volumes:
  db:
    name: ocw_db_data
  minio:
    name: ocw_minio_data
