version: "3.8"

services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
    env_file: .env.docker
    networks:
      - api_network
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - 8888:8080
    env_file: .env
    depends_on:
      - database
      - minio
    networks:
      - api_network
  database:
    ports:
      - 5433:5432
    image: postgres:alpine3.17
    networks:
      - api_network
    volumes:
      - db:/var/lib/postgresql/data
    env_file: .env.docker

networks:
  api_network:
    name: ocw_network

volumes:
  db:
    name: ocw_db_data
  minio:
    name: ocw_minio_data
