FROM golang:1.20.0-alpine3.17 AS build

RUN apk add --update make
RUN apk add --update git

COPY . /app
WORKDIR /app

RUN go get
RUN go install github.com/swaggo/swag/cmd/swag@v1.8.10
RUN go install github.com/google/wire/cmd/wire@latest

RUN make test-dependency

CMD [ "make", "test" ]